apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-operator.fullname" . }}-metrics-service
  labels:
    {{- include "grafana-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kubeRbacProxy.service.type }}
  ports:
    - port: {{ .Values.kubeRbacProxy.service.port }}
      targetPort: metrics
      protocol: TCP
      name: https
  selector:
    {{- include "grafana-operator.selectorLabels" . | nindent 4 }}
