changelog:
  exclude:
    labels:
      - documentation
      - chore
      - refactor
      - release-ignore
  categories:
    - title: Features
      labels:
        - 'feature'
    - title: Fixes
      labels:
        - 'bugfix'
    - title: Dependencies
      labels:
        - dependencies
