apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: grafana-operator
  name: grafana-operator-operator-metrics-service
spec:
  ports:
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: metrics
    - port: 8888
      targetPort: pprof
      protocol: TCP
      name: pprof
  selector:
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: grafana-operator
status:
  loadBalancer: {}
