resources:
  - ../../../config/crd
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - rolebinding.yaml
  - ../../../config/rbac/role.yaml
patches:
  - target:
      kind: ClusterRole
    patch: |
      - op: replace
        path: /metadata/name
        value: grafana-operator-permissions
