apiVersion: v1
kind: Service
metadata:
  name: grafana-operator-metrics-service
  labels:
    app.kubernetes.io/name: grafana-operator
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: grafana-operator
