apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-operator
roleRef:
  name: grafana-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: application-monitoring
userNames:
  - system:serviceaccount:application-monitoring:grafana-serviceaccount
