apiVersion: v2
name: grafana-operator
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 3.1.0

keywords:
- grafana
- alertmanager
- operator
- monitoring
home: https://github.com/integr8ly/grafana-operator
icon: https://grafana.zoom.us/w_p/232149086/9178c3c0-ba44-4fb7-9155-f92e2e080b37.png
sources:
- https://github.com/integr8ly/grafana-operator

maintainers:
  - name: cellebyte
    url: https://github.com/Cellebyte