apiVersion: v1
kind: Service
metadata:
  labels:
    application-monitoring: "true"
  name: {{ .GrafanaServiceName }}
  namespace: {{ .Namespace }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: grafana-k8s-tls
spec:
  ports:
  - name: web
    port: 9091
    protocol: TCP
    targetPort: gproxy
  selector:
    app: grafana