apiVersion: v1
kind: Service
metadata:
  labels:
    application-monitoring: "true"
  name: {{ .GrafanaServiceName }}
  namespace: {{ .Namespace }}
spec:
  type: {{ .GrafanaServiceType }}
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: grafana-http
  selector:
    app: {{ .PodLabelValue }}