kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: {{ .GrafanaAuthProxyDeploymentName }}
  name: {{ .GrafanaAuthProxyConfigMapName }}
  namespace: {{ .Namespace }}
data:
  config.yaml: |
    issuer: http://{{ .GrafanaAuthProxyConfig.Host }}
    
    storage:
      type: kubernetes
      config:
        inCluster: true
    
    web:
      http: 0.0.0.0:80
    
    frontend:
      theme: ccloud
      issuer: "Converged Cloud Grafana"
    expiry:
      signingKeys: "1m"
      idTokens: "2m"
    
    logger:
      level: debug
    connectors:
{{ .GrafanaAuthProxyConfig.Connectors | indent 4  }}
    oauth2:
      skipApprovalScreen: false
      passwordConnector: keystone
      responseTypes: ["code", "token", "id_token"]
    
    staticClients:
    - id: grafana
      name: Grafana UI
      redirectURIs:
      - http://{{ .Hostname }}/login/generic_oauth
      secret: {{ .GrafanaAuthProxyConfig.ClientSecret }}