apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: {{ .GrafanaAuthProxyDeploymentName }}
    namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .GrafanaAuthProxyDeploymentName }}
  template:
    metadata:
      labels:
        app: {{ .GrafanaAuthProxyDeploymentName }}
    spec:
      serviceAccountName: grafana-dex # This is created below
      containers:
      - image: hub.global.cloud.sap/monsoon/dex:8373c31b3e2d96ad3a7313227aa1bb8c59ddca39
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /keys
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /keys
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: secret
          mountPath: /etc/dex
      volumes:
      - name: config
        defaultMode: 420
        configMap:
          name: {{ .GrafanaAuthProxyConfigMapName }}
          items:
          - key: config.yaml
            path: config.yaml
      - name: secret
        secret:
          secretName: grafana-proxy
          items:
          - key: ca.crt
            path: ca.crt