apiVersion: disco.stable.sap.cc/v1
kind: Record
metadata:
  name: "{{ .Values.record.name }}"
  namespace: {{.Release.Namespace}}
spec:
  type: CNAME
  record: "{{ .Values.record.record }}"
  hosts:
    - "{{ .Values.record.host }}"