apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: grafana-operator
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - configmaps
  - secrets
  - serviceaccounts
  - namespaces
  - rolebindings
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
  - patch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
  - create
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
  - patch
- apiGroups:
  - integreatly.org
  resources:
  - grafanas
  - grafanas/status
  - grafanas/finalizers
  - grafanadashboards
  - grafanadashboards/status
  - grafanadatasources
  - grafanadatasources/status
  - grafanaproxies
  - grafanaproxies/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  - grafanaproxies
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - dex.coreos.com
  resources:
  - '*'
  verbs:
  - '*'