name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ./cmd/manager/ # <-- path to the directory containing the main() function
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  container-images:
    name: Build and push container images
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: quay.io
      PROJECT: gcp-tqt-prd-app
    steps:
      - name: Clone repo and checkout submodules
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: setup submodule 
        run: make submodule

      - name: build docker image
        run: docker-build IMG=us.gcr.io/${PROJECT}/grafana-operator:4.0.0

      - name: push the image to the container registry 
        run: docker push us.gcr.io/${PROJECT}/grafana-operator:4.0.0

      - name: Get version
        id: get_version
        shell: bash
        run: echo "::set-output name=version::$(make version)"

      - name: Tag release
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.TQT_GITHUB_ACTION_REPO_TOKEN }}
          custom_tag: ${{ steps.get_version.outputs.version }}
